[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:ybarsotti/nvim.git"
    refreshPeriod = "1h"
[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]
[".config/btop/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/btop/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]
[".config/git/delta/themes/catppuccin.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-nerd-font-window-name"]
    type = "git-repo"
    url = "https://github.com/joshmedeski/tmux-nerd-font-window-name.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/vim-tmux-navigator"]
    type = "git-repo"
    url = "https://github.com/christoomey/vim-tmux-navigator.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-sessionx"]
    type = "git-repo"
    url = "https://github.com/omerxx/tmux-sessionx.git"
    refreshPeriod = "168h"
